

service: escamedmobileapi # NOTE: update this with your service type

provider:
  name: aws
  runtime: python2.7
  region: eu-central-1
  memorysize: 128
  stage: expo
  timeout: 6
  environment:
    SQL_HOST: main.cxh7i7jlsgbr.eu-central-1.rds.amazonaws.com
    SQL_USER: engelstrompete
    SQL_PW: escagang69


#  vpc:
#      securityGroupIds:
#        - sg-9b4835f0
#      subnetIds:
#        - subnet-2feceb65


  iamRoleStatements: # IAM role statements so that services can be accessed in the AWS account
    - Effect: 'Allow'
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:eu-central-1:531284228182:table/*"
    - Effect: 'Allow'
      Action:
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:CreateNetworkInterface"
        - "ec2:DeleteNetworkInterface"
        - "ec2:DetachNetworkInterface"
      Resource:
        - "*"
    - Effect: 'Allow'
      Action:
        - "lambda:*"
      Resource:
        - "arn:aws:lambda:eu-central-1:531284228182:function:*"
    - Effect: 'Allow'
      Action:
        - "cognito-sync:*"
      Resource:
        - "*"
    - Effect: 'Allow'
      Action:
        - "cognito-identity:*"
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - "execute-api:Invoke"
      Resource: "arn:aws:execute-api:us-central-1:*:*"


package:
  exclude:
    - pulp/solverdir/cbc/win/**
    - pulp/solverdir/cbc/osx/**

functions:
  generate:
    handler: handlers.generate
    description: main function to generate for a
    memorySize: 1536
    timeout: 300
    environemnt: cat
    events:
      - http:
          path: generate
          method: POST
          integration: lambda

  regenerate:
    handler: handlers.regenerate
    description: regenerates a category
    memorysize: 512
    timeout: 30
    events:
      - http:
          path: regenerate
          method: POST
          integration: lambda
          authorizer:
            type: aws_iam
          cors: true

  generate_for_next_week:
    handler: handlers.generate_for_next_week
    description: checks DDB for active users and generates for upcoming week. Is invoked by CloudWatch Events
    events:
      - schedule:
          rate: cron(0 10 ? * FRI *)
          enabled: false


  post_plan:
    handler: handlers.post_plan
    description: function to post a self-created plan
    events:
      - http:
          path: post_plan
          method: POST
          integration: lambda
          authorizer:
            type: aws_iam
          cors: true


  scan_bls:
    handler: mobileapi.scan_bls
    description: scan BLS
    events:
      - http:
          path: scan_bls
          method: POST
          integration: lambda
          authorizer:
            type: aws_iam
          cors: true


  reset_all_user_nutrients:
    handler: handlers.reset_all_user_nutrients
    memorySize: 128
    description: deletes all userNutrition datasets for all users every night at XXX o'clock
    events:
      - schedule:
          rate: cron(0 0 * * ? *)
          enabled: true

#  test_ddb_stream:
#    handler: catchstream.test_ddb_stream
#    description: detects new user sign up and invokes generate
#    memorySize: 128
#    events:
#      - stream:
#          type: dynamodb
#          arn: arn:aws:dynamodb:eu-central-1:531284228182:table/UserDataTable/stream/2017-08-19T17:55:32.810

  invoke_generate_from_mobile_device:
    handler: handlers.invoke_generate_from_mobile_device
    description: invokes generate, used after sign up and in case no plan
    memorySize: 128
    timeout: 300
    events:
      - http:
          path: invoke_generate_from_mobile_device
          method: POST
          integration: lambda
          authorizer:
            type: aws_iam

  nutrients:
    handler: mobileapi.nutrients
    events:
      - http:
          path: get/nutrients
          method: GET
          authorizer: aws_iam
          integration: lambda
          cors: true


  allergies:
    handler: mobileapi.allergies
    events:
      - http:
          path: get/allergies
          method: GET
          authorizer: aws_iam
          integration: lambda
          cors: true

  habits:
    handler: mobileapi.habits
    events:
      - http:
          path: get/habits
          method: GET
          authorizer: aws_iam
          integration: lambda
          cors: true


  intolerances:
    handler: mobileapi.intolerances
    events:
      - http:
          path: get/intolerances
          method: GET
          authorizer: aws_iam
          integration: lambda
          cors: true


  container_categories:
    handler: mobileapi.container_categories
    events:
      - http:
          path: get/container_categories
          method: GET
          authorizer: aws_iam
          integration: lambda
          cors: true

  input_range:
    handler: mobileapi.input_range
    events:
      - http:
          path: get/input_range
          method: GET
          authorizer: aws_iam
          integration: lambda
          cors: true

  daily_top:
    handler: mobileapi.daily_top
    events:
      - http:
          path: get/daily_top
          method: GET
          authorizer: aws_iam
          integration: lambda
          cors: true

  home_slides:
    handler: mobileapi.home_slides
    events:
      - http:
          path: get/home_slides
          method: GET
          authorizer: aws_iam
          integration: lambda
          cors: true

  blood_pressure:
    handler: mobileapi.blood_pressure_for_week
    events:
      - http:
          path: blood_pressure
          method: POST
          authorizer: aws_iam
          integration: lambda
          cors: true

  blood_pressure_input_check:
    handler: mobileapi.blood_pressure_input_check
    events:
      - http:
          path: blood_pressure_input_check
          method: POST
          authorizer: aws_iam
          integration: lambda
          cors: true

  weight:
    handler: mobileapi.blood_pressurweighte_for_week
    events:
      - http:
          path: weight
          method: POST
          authorizer: aws_iam
          integration: lambda
          cors: true

  grocery:
    handler: mobileapi.grocery_url
    events:
      - http:
          path: post/grocery
          method: POST
          authorizer: aws_iam
          integration: lambda
          cors: true

  create_shopping_list:
    handler: mobileapi.create_shopping_list
    events:
      - http:
          path: shopping_list/create
          method: POST
          authorizer: aws_iam
          integration: lambda
          cors: true

  shopping_list:
    handler: mobileapi.shopping_list
    events:
      - http:
          path: shopping_list/get
          method: GET
          authorizer: aws_iam
          integration: lambda
          cors: true

   check_item:
    handler: mobileapi.check_item
    events:
      - http:
          path: shopping_list/check_item
          method: POST
          authorizer: aws_iam
          integration: lambda
          cors: true

